### ISSUE TITLE
建议答案解析支持html

### ISSUE THREAD

**Issue by MeanZhang** [PPeanutButter/exercise#6]
《2022肖秀荣1000题》里部分解析包含html，APP没有渲染出来，希望可以支持html。
![Screenshot_2021-08-14-19-28-24-403_com peanut exercise](https://user-images.githubusercontent.com/40561709/129445308-53cc12ed-3639-4d3b-b9a6-f6625908ec24.jpg)

**Comment by PPeanutButter** [comment]
设置打开html渲染就行
